
server:
  port: 8087
spring:
  application:
    name: Billing
#  main:
#    web-application-type: reactive
  datasource:
    url: jdbc:mysql://database-1.c7yocm6g6c1b.ap-south-1.rds.amazonaws.com:3306/erm
    username: admin
    password: Komorebi.Jisedai.2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  #  redis:
#    port: 6379
#  logging:
#  level:
#    org.springframework.cache: DEBUG

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    server:
      enable-self-preservation: false

#aws:
#  access:
 #   key:
 #     id: AKIA377NXCHOXUVLXXS2
 # secret:
 #   access:${AWS_ACCESS_KEY_ID}
 #     key: ${AWS_SECRET_ACCESS_KEY}
#  region: ap-south-1
#logging:
#  level:
#    org.springframework.security: DEBUG